openapi: 3.0.3
info:
  title: Boxed Hello
  description: function for greeting a person, but with a box around it.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: local
tags:
  - name: BoxedHello
paths:
  /boxedHello:
    post:
      operationId: sayHello
      tags:
        - HelloWorld
      summary: The main function
      description: This endpoint will call sayHello
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/Person'
      responses: 
        '200':
          description: OK
          content: 
            application/json:
               schema: 
                 $ref: './components.yaml#/components/schemas/Greeting'
        '400':
          description: input validation failed
          content:
            application/problem+json:
              schema:
                $ref: https://raw.githubusercontent.com/teamdigitale/api-openapi-samples/ea86b794105b4ecddacf19285c7975fc87154f98/external-apis/covid19-regione.umbria.it.yaml#/components/schemas/Problem